### ISSUE TITLE
USER STORY: Shopping Bag

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#14]
As a **Site User** I can **add books to a shopping bag** so that I can **make multiple book purchases and keep track of the total cost**.

## Acceptance Criteria
* Acceptance Criteria 1: Add to bag functionality added to the book detail page, with validation, which allows user to choose quantity and option for the book (if there is one) before adding to their bag.
* Acceptance Criteria 2: Bag icon on footer displays the running total for the user's shopping bag. 
* Acceptance Criteria 3: Clicking on the bag icon brings user to shopping bag page, where they can update quantity of, or delete items entirely from their bag.

## Dependencies
* EPIC: Initial Setup
* EPIC: Site Basics
* USER STORY: View Books

## Tasks
- [x] Create bag app. 
- [x] Create views, urls and templates for the bag functionality.
- [x] Add bag link/total count to the nav bar.
