### ISSUE TITLE
USER STORY: Checkout Page / Stripe

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#15]
As a **Site User** I can **view a checkout** so that I can **fill in delivery and payment info, see what I'm buying and how much it will cost **.

## Acceptance Criteria
* Acceptance Criteria 1: Checkout page includes a form with delivery and basic contact details.
* Acceptance Criteria 2: Stripe is used to process payments, with webhooks.
* Acceptance Criteria 3: An order summary is provided to user.
* Acceptance Criteria 4: Checkout button is added to the shopping bag page.
* Acceptance Criteria 5: Checkout success page is added to provide payment confirmation and order summary.

## Dependencies
* EPIC: Initial Setup
* EPIC: Site Basics
* USER STORY: View Books
* USER STORY: Shopping Bag

## Tasks
- [x] Create checkout app.
- [x] Add views, urls and templates for checkout and checkout success.
- [x] Setup Stripe to handle payments, including webhook setup.
- [x] Add checkout button to shopping bag page.
