### ISSUE TITLE
USER STORY: Toast Messages

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#18]
As a **Site User** I can **view toast** so that I can **easily see helpful messages regarding how I'm interacting with the site**.

## Acceptance Criteria
* Acceptance Criteria 1: By adding a message line to a view, the user will be shown a toast message at the top of their screen.
* Acceptance Criteria 2: The toast message design is customized through the templates folder.

## Dependencies
* EPIC: Initial Setup

## Tasks
- [x] Create a toasts folder in template to hold the custom toast html.
- [x] Edit settings.py to let Django know about our custom toasts.
- [x] Add toasts to views that user would find helpful to receive a feedback message about, eg order confirmations, shopping bag changes, account changes etc.
