### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#19]
As a **Site Owner** I can **receive favorable search engine rankings** so that I can **attract more customers**.

## Acceptance Criteria
* Acceptance Criteria 1: Add robots.txt file.
* Acceptance Criteria 2: Add sitemap.xml file.
* Acceptance Criteria 3: Add help meta info to HTML to increase SEO performance.

## Dependencies
* EPIC: Initial Setup

## Tasks
- [x] Add robots.txt file.
- [x] Add sitemap.xml file (will need need sitemap when new pages are added to the site).
- [x] Add meta data to base.html
