### ISSUE TITLE
USER STORY: Book & BookReview Model

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#2]
As a **Site Admin** I can **use Django models to store books and their reviews in the database** so that I can **simply and speed up my database entry, alteration, and maintenance.**.

## Acceptance Criteria
* Acceptance Criteria 1: The Book model includes, at least, the following fields: name, author, description, has_options, price, image_url and image.
* Acceptance Criteria 2: The 'price' field uses decimal field.
*  Acceptance Criteria 3: The BookReview model includes, at least, the following fields: book, username, title, updated_on description, created_on and rating.
* Acceptance Criteria 4: The book and username fields are foreign keys to the book model and the user model.
* Acceptance Criteria 5: The 'updated_on' and 'created_on' fields are automatically populated with the current time.
* Acceptance Criteria 6: The Book model contains methods for calculating the average of the book's reviews and another model for calculating the total number or reviews the book has.

## Dependencies
* USER STORY: Django Setup & Deployment

## Tasks
- [x] In models.py file, import models and User.
- [x] Create a Book class that inherits Django's models.Model. 
- [x] Add the required fields to the Book model.
- [x] Add a __str__(self) method to just return the 'name' field of the Book. 
- [x] Create a BookReview class that inherits Django's models.Model. 
- [x] Add the required fields to the BookReview model.
- [x] Add a __str__(title) method to just return the 'name' field of the Book. 
- [x] Configure any limited choice fields, eg 'rating', in accordance with the Django documentation
- [x] Add the model methods mentioned above to the Book model.
