### ISSUE TITLE
USER STORY: Admin Site

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#3]
As a **Site Admin** I can **access the Django admin panel** so that I can **create posts and test the Book and BookReview's model fields functionality.**.

## Acceptance Criteria
* Acceptance Criteria 1: Using a superuser login, I can access the Django admin panel.
* Acceptance Criteria 2: The Book & Book Review models are visible in the admin panel.
* Acceptance Criteria 3: The list_display for the book admin should display the following fields: name, author, price, avg_rating, image and has_options. 
* Acceptance Criteria 4: The books are listed in order of the name field.
* Acceptance Criteria 5: I can successfully add a book to the Book model. At least one book should be created.
* Acceptance Criteria 6: I can successfully add a review to the BookReview model. At least one review should be created.

## Dependencies
* USER STORY: Django Setup & Deployment
* USER STORY: Book Model

## Tasks
- [x] Create Django superuser.
- [x] Register the Book and BookReview models in admin.py file.
- [x] Create BookAdmin class to handle the list_display requirements.
- [x] Order the BookAdmin class by book name.
- [x] Create a book so the Book model has some contents.
- [x] Create a review so the BookReview model has some contents.
