### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#5]
As a **Site User** I can **view a home page** so that I can **get a general understanding of the site's purpose**.

## Acceptance Criteria
* Acceptance Criteria 1: At website's root URL, there's a site logo and a brief description of the site's purpose.
* Acceptance Criteria 2: Display the 3 newest book additions to the site.

## Dependencies
* Epic: Initial Setup

## Tasks
- [x] Create class based view to render the index.html.
- [x] Create index.html, which includes logo, a brief description of the site's purpose, and displays the most recent 3 additions to the Book model.
- [x] Connect up URLs using the urls.py file and HTML templating.
