### ISSUE TITLE
USER STORY: View Books

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/paperback-pp5#8]
As a **Site User** I can **view the books** so that I can **see what books are for sale and get more information about the ones I'm interested in**.

## Acceptance Criteria
* Acceptance Criteria 1: All books can be viewed on a single page.
* Acceptance Criteria 2: That page should just show basic info about a book: cover image, title and price.
* Acceptance Criteria 3: That page should tell the user how many total books are on show and allow user to sort the books in terms of name and price (both ascending and descending).
* Acceptance Criteria 4: Clicking on a book on the above page will lead to a book detail page with further info about the book, including a description of the book, the author of the book, and if the book has paperback/hardcover options.

## Dependencies
* EPIC: Initial Setup

## Tasks
- [x] Create a view, url and template in the book app to display all books on one page.
- [x] Create a view, url and template in the book app to display book detail page.
- [x] Add code to view and template to allow sorting of the books.
